[package]
name = "mitmproxy"
license = "MIT"
repository = "https://github.com/mitmproxy/mitmproxy-rs"
publish = false

version = "0.1.18"
edition = "2021"
rust-version = "1.65.0"

authors = [
    "Fabio Valentini <decathorpe@gmail.com>",
    "Maximilian Hils <cargo@maximilianhils.com>",
]
exclude = [
    "/.github/",
    "/benches/",
    "/dist/",
    "/venv/",
    "/PUBLISHING.md",
    "/architecture.png",
    "/coverage.sh",
    "/echo_test_server.py",
    "/rustfmt.toml",
]

[dependencies]
anyhow = { version = "1.0.66", features = ["backtrace"] }
base64 = "0.13"
log = "0.4.16"
once_cell = "1"
pretty-hex = "0.3.0"
rand_core = { version = "0.6.3", features = ["getrandom"] }
smoltcp = "0.8"
tokio = { version = "1.17", features = ["macros", "net", "rt-multi-thread", "sync", "time", "io-util"] }
boringtun = { version = "0.5", default-features = false }
x25519-dalek = "2.0.0-pre.1"
async-trait = "0.1.58"
console-subscriber = { version = "0.1.4", optional = true }


[target.'cfg(windows)'.dependencies]
bincode = "2.0.0-rc.2"

[target.'cfg(windows)'.dependencies.windows]
version = "0.43.0"
features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
]

[dev-dependencies]
env_logger = "0.9"
rand = "0.8"
criterion = "0.4.0"

[[bench]]
name = "process"
harness = false

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[features]
tracing = ["console-subscriber"]

[workspace]
members = [
    ".",
    "test-client",
    "ffi",
    "windows-redirector",
]
