name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust: stable
          - os: macos-latest
            rust: stable
            args: --exclude windows-redirector
          - os: ubuntu-latest
            rust: stable
            args: --exclude windows-redirector
          - os: windows-latest
            rust: 1.65.0  # MSRV
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust toolchain
        run: rustup toolchain install ${{ matrix.rust }} --profile minimal
      - name: Run "cargo check"
        # the action-rs/cargo action adds inline annotations for "cargo check" output
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          toolchain: ${{ matrix.rust }}
          command: check
          args: --workspace --verbose ${{ matrix.args }}
      - name: Run "cargo test"
        # the action-rs/cargo action adds inline annotations for "cargo test" output
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          toolchain: ${{ matrix.rust }}
          command: test
          args: --workspace --verbose ${{ matrix.args }}

  clippy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Run "cargo clippy"
        # the action-rs/cargo action adds inline annotations for "cargo clippy" output
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          toolchain: stable
          command: clippy
          args: --workspace

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Run "cargo fmt"
        # the action-rs/cargo action adds inline annotations for "cargo fmt" / rustfmt output
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          toolchain: stable
          command: fmt
          args: -- --check
